language: android

env:
  matrix:
    - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-21.1.2
    - android-21
        
    - sys-img-armeabi-v7a-android-21
    
    # Additional components
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services
